version: '3.8'

services:
  telegram-bot:
    image: mediscraper/scraper-bot
    build: .
    depends_on:
      - scraper-service
    environment:
      - MODE=dev
      - PORT=8080
      - BOT_TOKEN=
      - DOMAIN=
      - SCRAPER_SERVICE_URL=http://localhost:81
    ports:
      - "8080:8080"

  scraper-service:
    image: mediscraper/scraper-service
    build: .
    environment:
      - MODE=dev
      - PORT=81
    expose:
      - "81"
    ports:
      - "81:81"